### ISSUE TITLE
I got a message "not found : 'get /robot' "

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#163]
![capture](https://user-images.githubusercontent.com/40124613/43746507-4fab4992-99aa-11e8-8068-e1a43efc4773.PNG)

The recursive program I was running was going into a wall and I tried using the reset button to restart the level and got this.

**Comment by eth-is-a-security** [comment]
This was the URL https://mathbot.com/robot

**Comment by giftedprimate** [comment]
@eth-is-a-security I confirm that this is a bug in the currently deployed version. The bug is not present in the pre-production site therefore it has been fixed with the new spa controller (not merged yet). It will be fixed with the next release. 

The stop button appears to be working fine, so just use that in the mean time. Otherwise you can return to the site without /robot and you will be fine.
