### ISSUE TITLE
Need to enable javascript and cookies

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#170]
Nick Szabo just mentioned that he doesn't have javascript or cookies enabled in his browser and is having trouble getting mathbot to work.

So first of all how awesome is it that Nick is interested in our project at all!

And secondly, if we need one or both of those, can we detect they are disabled and display a warning banner?

**Comment by s3rvant** [comment]
HTML has a <noscript> tag option so you can display stuff only if JavaScript is absent.

Also, since mathbot is loading JS from multiple locations it would be a good idea for JS located on the mathbot server to run a check of which files have been loaded in cases of browser extensions that block cross-domain files or extensions like No Script where the user can selectively allow specific files to load.

As for cookies you can use sessions to track the user server-side though logins won't be as persistent as with cookies. Doesn't hurt to use both.

**Comment by giftedprimate** [comment]
@JWWeatherman a solution for this issue is deployed to pre-prod, ready for inspection.

**Comment by JWWeatherman** [comment]
Very cool.
