### ISSUE TITLE
Conditionals are available on the recursion planet

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#184]
They should be hidden until the conditional planet. If they are used accidentally it causes weird jumping to upper left hand corner - compiler error.
![math_bot](https://user-images.githubusercontent.com/32912678/44223968-292f6a00-a157-11e8-89a0-90e50fb29973.gif)

**Comment by giftedprimate** [comment]
That weird jumping is related to not being able have a function with multiple colors. We will need to address this before moving on to arithmetic. It also may be advisable to add one more level of recursion with base cases. Currently both recursion and conditionals require us to check each step since the recursion has no base case.

In the mean time
