### ISSUE TITLE
Improve Splash Screen

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#4]
- Located in ui/src/components/Splash_screen.vue
- Would like to animate the space ship in ui/src/assets/assets.js to go the opposite direction around the portal.

**Comment by jaimefm** [comment]
I'd like to help with this issue. i think i got what you want. see images.. how far from the portal do you want the spaceship. 

![circle2](https://user-images.githubusercontent.com/40052732/41816205-cf9a6bae-7733-11e8-8f63-7548f15e9529.PNG)

![circle](https://user-images.githubusercontent.com/40052732/41816082-88aea2bc-7730-11e8-9381-1b59060f232a.PNG)

**Comment by jaimefm** [comment]
@giftedprimate. This was not an svg animation. Didn't realize that's what was desired. I just added css code to perform the animation of the existing image. 

The blackhole animation was just 0% -> rotate(0) to 100% -> rotate(360), and the spaceship I added  something like 0% -> rotate(0) translate(150) rotate(60) to 100% -> rotate(360) translate(150) rotate(60) 

I will figure out how to create an svg animation file for this issue. I am mostly an electronics guy with a C programming background.

**Comment by jaimefm** [comment]
@giftedprimate. see attached svg file. let me know if the relative size between the spaceship and portal is ok. 

i am running windows 8.1 and the animation worked with firefox and chrome, but did not work with IE11. i ran a search and looks like IE does not support animations in the SVG file. they recommend animating the svg with css.  

[Ship_Portal.zip](https://github.com/JWWeatherman/math_bot/files/2195487/Ship_Portal.zip)

**Comment by jaimefm** [comment]
are you suggesting inserting the svg code directly into css and animating the elements, or taking the individual portal and ship images and animating them independently. is there any difference? if its the latter i have code for it already.

**Comment by giftedprimate** [comment]
@jaimefm Yep, insert the SVG directly into the template, then insert your CSS into the style section. 

I can insert vue directives into svg code is the reason why I like the svg code in the components. 

Thanks!

**Comment by jaimefm** [comment]
@giftedprimate. i finally had some time to complete this task this weekend. and 1 more issue came up, and not sure if there is anything you want to do about it. 

Recall i had discovered that that IE does not support animations inside the SVG container, which necessitated using CSS to animate the svg. It turns out however that ONLY the EDGE version of IE, the window 10 version of IE i believe, supports animating SVG elements with CSS. And only an edge version that was released at the beginning of this year ... earlier versions do not. 

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/
![svg_support](https://user-images.githubusercontent.com/40052732/43042302-ec78e06e-8d2e-11e8-9206-b5f78ee3c058.PNG)

I only have IE11, so the animation still doesn't work for me. but in firefox and chrome it does work. 

So i already have code that i can push for you to review, but i wanted to ask if there is anything you think we could look at for earlier versions of IE. a static image of the portal and spaceship do show up. 

Another question, you have keyframe definitions in src\ui\App.vue, for the current splash screen. do you want me to move the new keyframe definitions to App.vue, or keep them in ui/src/components/Splash_screen.vue? 

thanks

**Comment by giftedprimate** [comment]
@jaimefm Let's go ahead and proceed with what you have. As long as the user can see the space ship and portal my guess is that will be sufficient for the time being. 

As for the css, feel free to remove the keyframe def from App.vue so long as everything works as expected. It was placed there before I had made the splash screen component. 

Also as an fyi, I updated our AuthService yesterday and merged it into master, now auth works with the new auth0 tenant.

**Comment by giftedprimate** [comment]
@jaimefm If you pulled down the master since my last merge it is probably because you will need to update your `keys.js` file with what is found in `example-keys.js`. Also be sure to change the `audience` property in the WebAuth config in `services/AuthService.js` (line 22) to match your tenant. I have already added this to the keys.js file locally so that it will be included in my next merge. 

If you have not pulled down my changes yet the error is because auth0  has shut down the lock version we were using so be sure to do a pull from master and  follow the above steps and you will be good to go.

I'm looking forward to checking out your changes!

**Comment by giftedprimate** [comment]
@jaimefm Looks great! You were able to get the scale just right. It is much smoother now as well!

Thanks for doing the research about browser support as well, that was tremendously helpful and informative. 

If your up for it we could sure use a full size robot with blinking eyes. Basically I'd like to replace the robot at the top of the grid with a full sized one where his body is behind the grid. I think it would be fun for him to have eyes that randomly look different directions and blink. If you are up for this task it would probably be a good idea to create a new component called 'Robot_mascot' (or something similar) that takes a single prop for changing its size, that way we will have the flexibility to use it for more cases. 

No pressure, or rush. 

Thanks!

**Comment by jaimefm** [comment]
@giftedprimate. I'm up for helping out. Do you need the bottom part of the robot drawn? I can't say that I have any artistic ability but with feedback I can probably come up with something. 

Can you send me all the different robot icons you have right now to have a starting point?

**Comment by giftedprimate** [comment]
@jaimefm awesome! 

If you go into `ui/src/assets/assets.js` there's a property called `robotImages` where you can find the links to the robot in the grid, this should give you a good reference for the robot body. The robot logo is the property called `instructionsRobot`. 

Thanks for the help on this!

**Comment by jaimefm** [comment]
@giftedprimate. attached is the complete robot in svg. no animations yet. but i wanted to make sure the robot was correct before going any further. fortunately most of the robot was actually already drawn, not just the head.. it was just hidden by the svg. i only had to create the legs and the door knob.
is the gap between the body and legs too much? any thing else? 

[instructionsRobot_Rev1.zip](https://github.com/JWWeatherman/math_bot/files/2239804/instructionsRobot_Rev1.zip)

by the way, as for the eyes moving, do you just want the eyes to move, or the complete visor, like in the down, right, and left images.

**Comment by giftedprimate** [comment]
@jaimefm The robot looks perfect!

The legs look proportionate to the robot in the grid, so I think they look great. After we implement the new component in the app it should be pretty easy to fine tune it then. 

I'd like for just the eyes to move around and blink without the visor. Basically I'd like to make the robot look alive, a mascot of sorts.  

Thanks!

**Comment by jaimefm** [comment]
@giftedprimate. attached is a couple of animation samples. blinking one eye, moving eyes, and cycling through the lines on the top of the head.. its an html file, it seems to be working fine with the latest firefox. but i have not put in any compatibility code yet. I'm sending it now so you can see what things look like and you can play with the parameters. other animations like blinking both eyes at the same time is easily doable, but not shown. 

I'm still trying to figure out how to cycle randomly through the animations. it seems i might need javascript to do that. i will investigate further.

So let me know what you think of the animations. the eye movement does not seem too natural to me. any tips on that animation?  i was going to try moving right, left, center. or a around small circle, maybe it will look like he's dizzy 

[robot_animation.zip](https://github.com/JWWeatherman/math_bot/files/2259601/robot_animation.zip)

**Comment by jaimefm** [comment]
@giftedprimate.  here are a couple more ideas implemented.

[robot_animation2.zip](https://github.com/JWWeatherman/math_bot/files/2260082/robot_animation2.zip)

**Comment by giftedprimate** [comment]
@jaimefm Looks like you are moving in the right direction, he is already looking more personable! 

As for the random animation, you are correct, that will require a little Javascript to make happen. We are using Jquery (it is imported globally) on this project so feel free to use there stuff if you'd like, but if you prefer a different animation library or just vanilla Js that is fine with me.

I think you are correct about the eye animation that it would be worth doing a little research about the best way to make the movement more natural. My only suggestion would be to look into moving the eyes on a sphere.

Also I really liked the blinking of the right eye in the first file you sent me, if you can mix that blink into both eyes with the eye movement that would be great. In the future I'd like to have the grid robot be able to blink his eyes also so this is going to kill two birds with one stone. 

The blinking antenna is a really nice touch! 

Thanks!

**Comment by jaimefm** [comment]
@giftedprimate. its been a while, i got a bit busy, but take a look at the animation in the attached file. i realized that CSS has a rotate3d function, so the eye movement could happen around a sphere as you suggested. we could tweak the parameters i used if needed. let me know what you think. 

i still need to look at the javascript stuff.. but, is the idea you'd like to implement, to randomly  cycle through the different animations? the three current animations being, blinking, moving from right to left, and the light beam animation? or just activate the existing animation at random intervals. 

any other additions to the animation?

[robot_animation1.zip](https://github.com/JWWeatherman/math_bot/files/2289258/robot_animation1.zip)

**Comment by giftedprimate** [comment]
@jaimefm Looks really good!

How difficult would it be to have him look up and down as well? I think that would be the final touch for this animation.

As for the JavaScript, I'd like to randomly cycle through the animations and at random intervals. The goal to make him look very natural. 

Looking good! And no worries about the delay.

Thanks.

**Comment by jaimefm** [comment]
@giftedprimate. i have been struggling a bit with trying to animate the svg elements at a random interval. I'm not sure if the solution i found is optimal, but its really the only thing that i found that worked for me. This CSS/Javascript thing is new to me so there may be better solutions. My concern with the solution i have that it may waste too much memory and without knowing how the browser handles memory allocations, I'd be concerned about what will happen after running an extended period of time. take a look and let me know if you have any other ideas. 

The code clones the animation object, then removes the old one. The animation only runs once and stops. the attached code only runs one animation over and over at an interval of 7-10 seconds. i still need to randomize the animation selection, but that seems straightforward given that the animation can now actually restart. 

In addition i found a jquery keyframe plugin. main feature that it appears to have is that it auto-prefixes the css commands, so you would no longer have to have webkit, moz, o, prefixes, and multiple keyframe definitions for the same animation. It says this in a comment in the readme, i haven't looked at the code to verify that though.  if this is not that important i can try just with javascript, but i imagine it would just add a bit more code to test for each browser to be able to select the right animation prefix. 
https://github.com/Keyframes/jQuery.Keyframes

i tested with firefox and chrome in windows 8.1


[robot_animationJS_random1.zip](https://github.com/JWWeatherman/math_bot/files/2355950/robot_animationJS_random1.zip)

**Comment by giftedprimate** [comment]
@jaimefm I would just stick with CSS for the animations and just use jquery's .addClass and .removeClass selectors to remove/apply the animation. Just using pure CSS for adding and removing animations has proven to be more efficient for me and a little easier for other devs to reason about. Below is how I'd approach the problem.

1 - Create a CSS selector for each of the animations
2 - Create a function that gets a random int between 0 and array.length - 1
3 - Create a function that creates a random time interval (maybe between 1000ms and 10000ms to start)
4 - Create a function that adds class to html element
5 - Create a function that removes class from html element
6 - Create a function that uses above functions to remove previous animation (.removeClass) apply animation class using JQuery (.addClass) then use setTimeout with random interval to call self. Since this function is recursive you could give it a parameter for the current index. 

You are pretty much doing this already, the main thing to add is selecting the animation randomly from the array and just use CSS selectors instead of JQuery key frames.

Also while I have you. You are earning Powerups (Mathbot tokens) by working on this problem for us. To get your power ups file and issue similar to #218 and assign it to jordanBTCplz.

**Comment by jaimefm** [comment]
@giftedprimate. thank you for the detailed response. i actually did try the addClass and removeClass but was unsuccessful at restarting the animation. I will try that option again as i might have been doing something wrong. 

About the powerups. thank you for making me aware of them. At some point if i continue to do more work on mathbot i may apply for it. but for now, a lot of the time i've put in has really just coming up to speed with the tools, git, svg, css, javascript, and just looking through the code base.

**Comment by jaimefm** [comment]
@giftedprimate. looks like the issue i was having with the addClass/removeClass functions was that i was unable to restart (or remove then add) the SAME animation. however if remove a class then add a different one, i could get the code to restart the animations indefinitely. so i added code to prevent the same animation from running 2 times in a row. take a look at the attached code and let me know what you think. two main things left would be to add all the browser compatibility prefixes, and just double check that the animation axis of rotations are centered properly. something looked a bit off.. also let me know if you want to change the timing of the animations or any other updates. 

[robot_animationJS.zip](https://github.com/JWWeatherman/math_bot/files/2369433/robot_animationJS.zip)

**Comment by giftedprimate** [comment]
@jaimefm You nailed it!

Now if you can make a Vue component with the code in the `ui/src/components`. A good way to work on components like this without having the entire application to deal with is to setup a separate 'sandbox' to work in. Here's a tutorial that will show you how to build a vue app with vue-cli, https://flaviocopes.com/vue-cli/, its really easy.

About the Powerups, you are certainly free to claim some of them even for your learning time, we are just glad to have the help and we fully expect that allot of developers will have to spend a little time learning the tech (we didn't exactly go main stream!). The Powerups will allow you to share in the future tips we receive.

**Comment by giftedprimate** [comment]
moving this conversation to #135
