### ISSUE TITLE
When you delete a function it stays in main in a weird state

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#415]
I'm not sure how we should deal with this. I think we should probably remove it from "main" on all levels and also ask for confirmation that they want to delete the function?

https://drive.google.com/open?id=1FrV7qqjYqgU011Qv92wlEekMWSA8b6ZD

**Comment by giftedprimate** [comment]
@JWWeatherman This is just an over site on my part, to solve this I need to recursively iterate through all the functions and delete that function. On that note, I do believe we should do some sort of confirmation before deleting the function because it could have major implications.

I think the feature is still worth implementing especially as the students progress.

**Comment by giftedprimate** [comment]
@JWWeatherman A solution for this is deployed to preprod, without the alert, after building it I realized it may not be worth it.

**Comment by JWWeatherman** [comment]
@giftedprimate I think we better confirm since removing it will nuke any functions that rely upon it. Hit this myself once or twice already.

**Comment by giftedprimate** [comment]
Closing since this is in production. Last comment is being handled with issue #451
