### ISSUE TITLE
Introducing all the basic elementary operations at preliminary level.

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#45]
2.	Walking for 4 stages seemed a little bit boring. Instead introduce all the basic elementary operations in first 3/4 stages (Walk and Turn Right). And then start making functions with these elements. Thus a clear distinction between elementary operations and functions will be created through the process in their mind.

**Comment by JWWeatherman** [comment]
We actually srarted with that, but since we are targeting kids as young as 5 we found that a slower build works better fot them. And we hope its fast enough for more capable students to get through wuick.

We could introduce different experiences for different personas, but we hope we can avoid that.
