### ISSUE TITLE
Maintaining function heirarchy

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#46]
While creating the first function, I feel it would be better to represent the function hierarchy. Instead of showing the functions at the same level with the elementary operations, separated by a vertical green line, it would be better to show the function on top of the elementary operations. This representation will make it clear that the “Functions” are basically higher order abstraction of “Elementary” operations. Why not let kids build all the Functions (Rocket, U-turn and Left-turn) on their own step by step, instead of providing those. This hierarchical representation can also be maintained letter on when they will build some more complex functions using Rocket, U-turn and Left-turn, which will then be added above these functions.  

![issue4](https://user-images.githubusercontent.com/36541669/40654535-354a1076-635c-11e8-9be8-e0eb90b28459.PNG)

**Comment by giftedprimate** [comment]
We build the rocket function for the student in order to demonstrate what a function is. The 'U Turn' and 'Turn Left' functions are in fact built by the student as is, the only thing we do for the student is name them. Any future functions a user creates will be built in the same manner.

As for hierarchy, in functional languages everything is a function, therefore there is no true hierarchy. That said I have felt that we need a better way to differentiate between user generated 'functions' and built in 'methods' and this is where the green bar came into play.  We will need to defer to a designer for help with this in order to maintain positioning on all devices.

**Comment by giftedprimate** [comment]
@codeShark149 Just letting you know that we have differentiated between primitives and the created functions. You can expect to see this change in the next release.
