### ISSUE TITLE
The area that causes scrolling right and left is too small

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#619]
This might be harder to fix than it is worth right now, but if we can make it easier to scroll left and right it would be cool.

https://drive.google.com/file/d/1gq1nmvbIq9yT8jdW0KI2MSa9WOenzQld/view?usp=sharing

**Comment by giftedprimate** [comment]
I'll take a look at this today, but this may not be something we can control because that sort of scroll behavior is handled by the browser.

**Comment by JWWeatherman** [comment]
That’s totally fine. If it’s not configurable without doing something crazy, close it.

**Comment by giftedprimate** [comment]
Cool, I'll take a look at it today, there may be some css selector I don't know about that will widen that area. If I start writing overly 'clever' code then I'll stop.

**Comment by giftedprimate** [comment]
Re-assigning this to @willweatherman since he will be free shortly.

**Comment by giftedprimate** [comment]
@willweatherman take a look at this and figure it out for me. The fix for this is going to be adding some new options to the draggables. There's an options object located in `Function_drop.vue`, `Commands.vue` and `Staged_functions.vue`.

Your going to want to check out the docs at https://github.com/SortableJS/Sortable#options and https://github.com/SortableJS/Vue.Draggable. Also be sure to read through the issues (closed ones also) to see if anyone else has or is having the same issue.

![Uploading Screenshot from 2018-12-10 11-41-35.png…]()

**Comment by willweatherman** [comment]
Ok.

**Comment by giftedprimate** [comment]
@willweatherman if you can't make this work in less than 4 hours go ahead and re-assign this back to me.

Thanks!

**Comment by giftedprimate** [comment]
@willweatherman also don't do anything with the lists, try to solve this with just the draggable options or plain css.

**Comment by willweatherman** [comment]
@giftedprimate  HI I finished this one and I created a pull request.

**Comment by willweatherman** [comment]
I messed with the dragable options to thats it.

**Comment by giftedprimate** [comment]
@willweatherman this issue has nothing to do with staged functions, those ones should not be sortable. 

I am re-assigning this to myself. 

Thanks!

**Comment by giftedprimate** [comment]
@JWWeatherman this was only happening in the main function. The cause was due to over nesting in the html. The reason this was the case was because of past refactoring. 

Deployed to pre-prod.

**Comment by JWWeatherman** [comment]
Looks good.
