### ISSUE TITLE
Conditional error

### ISSUE THREAD

**Issue by willweatherman** [JWWeatherman/math_bot#653]
Hi,

When A conditional function is false instead of skiping and moving on it places the robot in the top left corner of the grid even if there is a barrier there.

https://drive.google.com/file/d/1Axy3whA_gYn4HvQmsgIrt-fPEC9_Gz-W/view?usp=sharing

This is a mute video showing the error.

I am using a mobile hotspot with 4.5 MBPS download and 12 MBPS upload.

When running matbot on my laptop I see no errors in the sbt shell or the console.

The robot instead of moving past a false conditional put the robot in the top left corner.

**Comment by willweatherman** [comment]
Not sure what priority this should be but this is my guess.

Thanks-
Will.

**Comment by console-rastling** [comment]
Ah. I know what this is. If you can make a program where the robot never moves, his position initializes to 0,0 because no frames ever get generated.  This may have been fixed with the speed control slider because to support reverse operation the processor now always generates a first frame before the robot starts moving so that we can always reverse back to the start position. This bug may already be fixed. I like bugs like that!

**Comment by giftedprimate** [comment]
I'll move to the scrub-through branch in a minute to confirm.

**Comment by giftedprimate** [comment]
Nope, it doesn't happen on the scrub-through branch.

**Comment by giftedprimate** [comment]
@willweatherman @console-rastling this will in fact be remedied after we merge scrub-through with master. It actually is probably safe to do so now however I'd like to wait til console is finished with the compiler upgrades for this feature.

**Comment by JWWeatherman** [comment]
Dropped priority since this is a bug in the code Will was trying to run on mathbot not a mathbot bug. Will be a much better UX on error when we have scrub through though.

**Comment by giftedprimate** [comment]
This bug has been solved in scrub-through and is deployed to pre-prod.

**Comment by JWWeatherman** [comment]
Awesome.
