### ISSUE TITLE
Video hint default settings

### ISSUE THREAD

**Issue by j-chimienti** [JWWeatherman/math_bot#663]
Suggestions from teacher friend:

1. hide length of video, as kids will see 30 seconds and will tune out

1. kids need words, caption the video on default.

**Comment by JWWeatherman** [comment]
These are interesting ideas. I don't think we should hide the length of the video (not sure it is even possible on youtube) because we want to allow them to scrub through to the parts that they want to see. Regarding captions most kids that I've observed can't read very quickly and they tend to fast forward/rewind to just the part that shows what they want to see. They ignore a lot of me talking already.

Over time we will get more feedback that solidifies what we should do here, but for now I'm going to close this one.
