### ISSUE TITLE
unable to drag and drop a function from a user defined function 

### ISSUE THREAD

**Issue by j-chimienti** [JWWeatherman/math_bot#725]
When trying to drop a function from a user defined function, sometimes the function isn't removed, but is appended to end

https://drive.google.com/file/d/1d7X0VJAH_Fj6Ws-UmbCXjcdkIm0HbLyI/view

https://drive.google.com/file/d/1T5-LdwEsFH_8JJ0vFF-7W9VwyjvRJYkf/view

**Comment by giftedprimate** [comment]
My theory as to what is happening is that the activate function component is activating along with the trash component. This is next on my que.

**Comment by giftedprimate** [comment]
The problem is actually coming from the cursor still bring inside the draggable but the droppable is outside the list. This causes the droppable to go the the end of the list. 

I will explore the idea of putting the ghost back in so that there is a visible indicator of where the droppable is located.

**Comment by giftedprimate** [comment]
@j-chimienti can you confirm that your cursor was outside the draggable zone?

**Comment by j-chimienti** [comment]
My cursor was outside the draggable zone.

I revisited today, and was unable to recreate error. The functions are dropped when more than half of icon is outside zone, and not seeing any bugs

https://drive.google.com/file/d/1o193-4ELqbWgn_x9CWx1j_foWOQM68c0/view?usp=sharing

**Comment by giftedprimate** [comment]
Awesome, my favorite kind of bug! Thanks man.
