### ISSUE TITLE
Console Compensation Request Through 12/15

### ISSUE THREAD

**Issue by PedroXimenez** [JWWeatherman/math_bot#731]
Console, we would like to keep up with this on a monthly basis, but for this request, please post your reward request and a brief explanation of the tasks completed for the following time periods:

8/16 - 9/15
9/16 - 10/15
10/16 - 11/15
11/16 - 12/15

When finished, please paste in your Indie Square wallet address that you want your tokens sent to and assign this issue to JW.

**Comment by PedroXimenez** [comment]
@console-rastling 
Please confirm if the calculation below looks accurate for your hours for the time period 8/16 - 12/15:
17 wks * 6 hrs/wk * $150/hr  = $15,300
Thanks.

**Comment by console-rastling** [comment]
Summary of contributions:

- Move authentication in house. #73  ~43 hours (8/20 and 10/29)
- Compiler stops responding on long recursive functions.#504 ~9 hrs (8/21-8/28)
- Build a Lisp interpreter server side #373 ~22 hrs (9/11-11/20)
- Highlight the command the robot is currently executing (feature idea) #442 ~6 hrs (11/26-11/27)
- Need a "holding anything" conditional #437 ~3 hrs (12/3)
- MBL: Change function syntax JWWeatherman #589 ~3 hrs (12/4)
- Need new denomination blocks in sandbox #627 ~6 hrs (12/10-12/11)

The hours and time periods are all approximate because I had to go through the git logs. During that time, I also remember dealing with some operational issues.  Since I'm just starting now to create a more complete diary my future summaries will include those things too. 

It's fun to look back.  #73 was challenging because we had to research how to oauth to Github and learn to fake and migrate the "local" login provided by Auth0. #373 was fun because of learning the parser library (it's a very cool scala thing) and adding a little more formal architecture to the "compiler" and "processor" to support MBL.  I honestly had my doubts it was possible.

**Comment by PedroXimenez** [comment]
@console-rastling 
Console, that's awesome! Thank you for the detailed update.

**Comment by PedroXimenez** [comment]
@console-rastling
Would you also please verify that 1Gk3Vew7HeGu16xYaLpE1Xpw4tZrvYf5YA is still a good address for you?

**Comment by console-rastling** [comment]
Yes. Still good.

**Comment by PedroXimenez** [comment]
Excellent, thanks!

**Comment by PedroXimenez** [comment]
@console-rastling 
Console, just wanted to verify that you received the tokens?

**Comment by console-rastling** [comment]
Yes. Looks like I got them.

**Comment by PedroXimenez** [comment]
Great, thank you!
